//AUTH
export const SET_USER = "SET_USER";
export const SET_USERS = "SET_USERS";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const SUCCESS_REGISTER =  "SUCCESS_REGISTER";
export const FAIL_REGISTER =  "FAIL_REGISTER";
export const SUCCESS_LOGIN = "SUCCESS_LOGIN";
export const FAIL_LOGIN = "FAIL_LOGINR";
export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

//Promeni lozinka
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";
export const SET_CHANGING = "SET_CHANGING";

//Messages:
export const SUCCESS_ADD_MESSAGE =  "SUCCESS_ADD_MESSAGE";
export const SUCCESS_DELETE_MESSAGE = "SUCCESS_DELETE_MESSAGE";
export const SET_MESSAGES = "SET_MESSAGES";
export const SET_GROUP = 'SET_GROUP';
export const SET_GROUPS = 'SET_GROUPS';
export const SET_ACTIVE_MESSAGES = "SET_ACTIVE_MESSAGES";
export const SET_NEWCHAT_MSG = "SET_NEWCHAT_MSG";
export const ADD_NEW_GROUP = "ADD_NEW_GROUP"; 
export const UPDATE_GROUP = "UPDATE_GROUP";
export const SUCCESS_CHANGE_GROUP = "SUCCESS_CHANGE_GROUP";
export const SET_NEW_GROUP = "SET_NEW_GROUP";
export const SET_SEEN_MESSAGE = "SET_SEEN_MESSAGE";
export const SET_SEEN_GROUP = "SET_SEEN_GROUP";
export const SET_SEEN_SOCKET = "SET_SEEN_SOCKET";
export const SET_REFRESH_GROUPS = "SET_REFRESH_GROUPS";